package com.exercise.music_exercise

class AppContents {
    companion object{
        const val INTENT_DATA_LIST_INDEX = "INTENT_DATA_LIST_INDEX"
        const val INTENT_DATA_LIST_POSITION = "INTENT_DATA_LIST_POSITION"
        const val INTENT_DATA_EDIT_MODE = "INTENT_DATA_EDIT_MODE"
        const val INTENT_DATA_LIST_TITLE = "INTENT_DATA_LIST_TITLE"
        const val INTENT_DATA_GROUP_INDEX = "INTENT_DATA_GROUP_INDEX"
        const val INTENT_DATA_CHECK_GROUP_INDEX = "INTENT_DATA_CHECK_GROUP_INDEX"
        const val INTENT_DATA_VIEW_TYPE = "INTENT_DATA_VIEW_TYPE"
        const val INTENT_DATA_PLAY_LIST = "INTENT_DATA_PLAY_LIST"

        const val RESULT_DATA_TITLE = "RESULT_DATA_TITLE"
        const val RESULT_DATA_LISTDATA = "RESULT_DATA_LIST_DATA"
        const val RESULT_DATA_HEALTHLIST = "RESULT_DATA_HEATHLIST"

        const val VIEWTYPE_DATEHADER = 0
        const val VIEWTYPE_PLAYITEM = 1
    }
}